api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/modules/controleonline/dashboard/src/Entity",
                "%kernel.project_dir%/modules/controleonline/dashboard/src/Resource",
            ]
    
