api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/dashboard/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/dashboard/Resource",
            ]
    
